### ISSUE TITLE
How do you set the Log URL based on output from a previous step?

### ISSUE THREAD

**Issue by NullVoxPopuli** [deliverybot/deployment-status#1]
I have dynamic subdomains / deploys with netlify, and I can get the URL from the deploy output via `jq`. So, in the previous step, I have an environment variable that has the deploy URL. But... I don't know how to get it into the next step.

**Comment by colinjfw** [comment]
Hey thanks @NullVoxPopuli  for the first issue!

I don't know much about some of the more complex parts of GitHub actions. I do believe you can set the "output" of a script (ie. setting a url) and then maybe pass it back in as a step variable?

There is code for this in the toolkit:
https://github.com/actions/toolkit/blob/master/packages/core/src/core.ts#L88

And then you could maybe include this by grabbing the output from the steps object.
```yaml
with:
  url: ${{ steps.url }}
```

There may be a better approach to this.

**Comment by chrnorm** [comment]
@NullVoxPopuli I recently ran into this issue in my CI pipeline using the zeit now CLI to deploy my frontend. My workaround was to set my environment variable as an output from my run step in my job as follows:
```yaml
- name: Export URLs to environment variables
        id: url
        run: |
          FRONTEND_URL=mysite.com # replace this with your jq command
          echo ::set-output name=frontend_url::${FRONTEND_URL}
```

then you can use it in the deliverybot action as follows (untested!):
```yaml
- name: 'deployment success'
      if: success()
      uses: 'deliverybot/deployment-status@master'
      with:
        log-url: ${{ steps.url.outputs.frontend_url }}
        state: 'success'
        token: '${{ github.token }}'
```

note that the `id` property of the url step must be set for you to reference it correctly in the deliverybot step. [Here's some more details about setting output parameters](https://help.github.com/en/articles/development-tools-for-github-actions#set-an-output-parameter-set-output).
