### ISSUE TITLE
Error when workflow is triggered from another repo

### ISSUE THREAD

**Issue by dreinhardt89** [deliverybot/deployment-status#10]
I have a repo that triggers a deployment workflow using benc-uk/workflow-dispatch@v1.

I trigger the deploy workflow like below:
```yaml
- name: Deploy
  uses: benc-uk/workflow-dispatch@v1
  with:
    workflow: Deploy
    token: ${{ secrets.pull_access_token }}
    repo: org/repo
    ref: master
    inputs: '{"environment": "all"}'
```

And have this step in the deploy workflow:
```yaml
- name: Deployment Pending
  uses: deliverybot/deployment-status@v1
  with:
    state: pending
    token: ${{ github.token }}
```

It seems to trigger just fine but I'm getting the below error on the deployment status step:
![image](https://user-images.githubusercontent.com/85892019/150844553-3adae24f-9bd1-42bd-a453-681e7722a6f3.png)

When I run the deploy workflow normally everything works fine.
